default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tel_med
  username: postgres
  password: root
  host: localhost # Update with your PostgreSQL host if necessary
  port: 5435 # Update with your PostgreSQL port if different

test:
  <<: *default
  database: tel_med
  username: postgres
  password: root
  host: localhost # Update with your PostgreSQL host if necessary
  port: 5435 # Update with your PostgreSQL port if different

production:
  <<: *default
  database: tel_med
  username: postgres
  password: root
  host: localhost # Update with your PostgreSQL host if necessary
  port: 5435 # Update with your PostgreSQL port if different